<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Possible_Attacks.php");
	include("$currDir/Possible_Attacks_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Possible_Attacks');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Possible_Attacks";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`Possible_Attacks`.`id`" => "id",
		"`Possible_Attacks`.`title`" => "title",
		"`Possible_Attacks`.`description`" => "description"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`Possible_Attacks`.`id`',
		2 => 2,
		3 => 3
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`Possible_Attacks`.`id`" => "id",
		"`Possible_Attacks`.`title`" => "title",
		"`Possible_Attacks`.`description`" => "description"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`Possible_Attacks`.`id`" => "ID",
		"`Possible_Attacks`.`title`" => "Attack type",
		"`Possible_Attacks`.`description`" => "Description"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`Possible_Attacks`.`id`" => "id",
		"`Possible_Attacks`.`title`" => "title",
		"`Possible_Attacks`.`description`" => "description"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Possible_Attacks` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 0;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 0;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Possible_Attacks_view.php";
	$x->RedirectAfterInsert = "Possible_Attacks_view.php?SelectedID=#ID#";
	$x->TableTitle = "Possible Attacks";
	$x->TableIcon = "resources/table_icons/bug.png";
	$x->PrimaryKey = "`Possible_Attacks`.`id`";

	$x->ColWidth   = array(  150, 150);
	$x->ColCaption = array("Attack type", "Description");
	$x->ColFieldName = array('title', 'description');
	$x->ColNumber  = array(2, 3);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Possible_Attacks_templateTV.html';
	$x->SelectedTemplate = 'templates/Possible_Attacks_templateTVS.html';
	$x->TemplateDV = 'templates/Possible_Attacks_templateDV.html';
	$x->TemplateDVP = 'templates/Possible_Attacks_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Possible_Attacks`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Possible_Attacks' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Possible_Attacks`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Possible_Attacks' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Possible_Attacks`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Possible_Attacks_init
	$render=TRUE;
	if(function_exists('Possible_Attacks_init')){
		$args=array();
		$render=Possible_Attacks_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Possible_Attacks_header
	$headerCode='';
	if(function_exists('Possible_Attacks_header')){
		$args=array();
		$headerCode=Possible_Attacks_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Possible_Attacks_footer
	$footerCode='';
	if(function_exists('Possible_Attacks_footer')){
		$args=array();
		$footerCode=Possible_Attacks_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>